openapi: 3.0.2
info:
    title: USS Qualifier webapp API
    version: 0.0.1
    description: >-
        This is an interface to run USS qualifier tests via uss_qualifier webapp.

components:
    schemas:
        TestRunSpecification:
            type: object
            properties:
                flight_records:
                    description: >-
                        List of flight record IDs.
                    type: array
                    items:
                        $ref: "#/components/schemas/FlightRecordID"
                auth_spec:
                    description: >-
                        User authentication specification.
                    type: string
                user_config:
                    description: >-
                        JSON string of configuration specifying which tests to run and how to run them.
                    type: string
        CreateTestRunRequest:
            type: object
            required:
                - specification
            properties:
                specification:
                    $ref: "#/components/schemas/TestRunSpecification"
        KmlImportJobsBatchCreateResponse:
            type: object
            properties:
                kml_import_job_id:
                    type: string
                status_message:
                    type: string
                    example: "A task has been started in the background."
                    description: >-
                        Status of currently running task.
                background_tasks:
                    type: array
                    items:
                        $ref: "#/components/schemas/TaskID"
                    description: >-
                        A list of task ids running in the background. The status of each such task can be checked through /api/tasks/<task_id>.
        FlightRecordsBatchCreateResponse:
            type: object
            properties:
                flight_record_ids:
                    type: array
                    items:
                        $ref: "#/components/schemas/FlightRecordID"
        TestRun:
            type: object
            properties:
                test_run_id:
                    $ref: "#/components/schemas/TestRunID"
                task:
                    type: object
                    properties:
                        id:
                            $ref: "#/components/schemas/TaskID"
                        status:
                            type: string
                status_message:
                    type: string
                    example: "A task has been started in the background."
                    description: >-
                        Status of currently running task.
                user_id:
                    type: string
                    description: >-
                        User ID of user running the tests.
                specification:
                    $ref: "#/components/schemas/TestRunSpecification"
                report:
                    type: object
                    description: >-
                        Content of test runs' json output file.
        ListTestRunsResponse:
            type: object
            properties:
                test_runs:
                    type: array
                    items:
                        $ref: "#/components/schemas/TestRun"
        TaskID:
            description: >-
                Identifier for a background task.
            type: string
            example: 2f8343be-6482-4d1b-a474-16847e01af1e
        TestRunID:
            description: >-
                Identifier of a test run.
            type: string
            example: 2022-04-06_235836_1.json
        FlightRecordID:
            description: >-
                Identifier of a flight record.
            type: string
            example: flight_1.json
        BackgroundTask:
            type: object
            properties:
                task_id:
                    $ref: "#/components/schemas/TaskID"
                task_status:
                    type: string
                    description: >-
                        Returns current status of the background task.
                    example: "Started|Finished"
                task_result:
                    type: object
                    description: >-
                        Tests result if task has completed.
                generated_flight_records:
                    type: array
                    items:
                        $ref: "#/components/schemas/FlightRecordID"
                    description: >-
                        List of generated flight record IDs if background task is for a KML import job.

paths:
    /test_runs:
        post:
            summary: /test_runs
            description: Start a new test suite run
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            $ref: "#/components/schemas/CreateTestRunRequest"
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TestRun"
                    description: Test execution request submitted successfully.
                "404":
                    description: Testing interface is not activated.
                "400":
                    description: Flight record not found.
        get:
            summary: /test_runs
            description: List existing test suite runs
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ListTestRunsResponse"
                    description: >-
                        List of test runs retrieved successfully.
    /test_runs/{test_id}:
        get:
            summary: /test_runs/{test_id}
            description: Get details of specific test suite run
            parameters:
                - name: test_id
                  in: path
                  required: true
                  description: Identifier of the test run of interest.
                  schema:
                      $ref: "#/components/schemas/TestRunID"
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TestRun"
                    description: >-
                        Test run retrieved successfully.
                "400":
                    description: Test execution not found.
    /tasks/{task_id}:
        get:
            summary: /tasks/{task_id}
            description: Get details of specific background task
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BackgroundTask"
                    description: >-
                        Background task retrieved successfully.
                "400":
                    description: Status is not avilable for task ID.
        parameters:
            - name: task_id
              in: path
              required: true
              description: A task ID of an initiated task.
              schema:
                  $ref: "#/components/schemas/TaskID"
    "/flight_records:batchCreate":
        post:
            summary: /flight_records:batchCreate
            description: Upload one or more flight records
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                files:
                                    type: array
                                    items:
                                        type: string
                                        format: binary
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/FlightRecordsBatchCreateResponse"
                    description: >-
                        Flight records created successfully.
                "400":
                    description: Failed to upload files.
    "/kml_import_jobs:batchCreate":
        post:
            summary: /kml_import_jobs:batchCreate
            description: Process one or more KML files into flight records
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                files:
                                    type: array
                                    items:
                                        type: string
                                        format: binary
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/KmlImportJobsBatchCreateResponse"
                    description: >-
                        KML conversion initiated successfully.
                "400":
                    description: Failed to upload files.

servers:
    - url: http://localhost:8072/api
      variables: {}
