name: Monitoring packages tests (python)
on:
  pull_request: # All
  push:
    branches:
      - master
jobs:
  monitoring-tests:
    name: Test monitoring packages
    runs-on: ubuntu-latest
    steps:
      - name: Job information
        run: |
          echo "Job information"
          echo "Trigger: ${{ github.event_name }}"
          echo "Host: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          docker images
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Monitorlib tests
        run: |
          cd monitoring/monitorlib
          make test
      - name: Run Mock USS tests
        run: |
          cd monitoring/mock_uss
          make test
      - name: Run USS Qualifier tests
        run: |
          cd monitoring/uss_qualifier
          make test